//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTrueProgramCodeService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebFormSubmission", Namespace="http://schemas.datacontract.org/2004/07/EfPosProgramConversion")]
    public partial class WebFormSubmission : object
    {
        
        private bool CalledFromMassageServiceField;
        
        private string CampaignAllocationCodeField;
        
        private string CampaignAllocationProgramsField;
        
        private string CampaignNameField;
        
        private string CityField;
        
        private string CommentsField;
        
        private string CountryCodeField;
        
        private string CustomerActivityTypeCodeField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        private int EFComRepresentativeMarket_IdField;
        
        private int EFComRepresentative_IdField;
        
        private string EfComMarketCodeField;
        
        private string EmailField;
        
        private string EnqFormTypeField;
        
        private string EntrySourceCodeField;
        
        private string FirstNameField;
        
        private int FormSubmission_idField;
        
        private string FormUrlField;
        
        private string GenderField;
        
        private int Infomeeting_IdField;
        
        private System.DateTime InsertDateField;
        
        private bool IsExpressCallField;
        
        private string LanguageCodeField;
        
        private string LastNameField;
        
        private int MyEFInvitationRepresentativeMarket_IdField;
        
        private int MyEFInvitationRepresentative_IdField;
        
        private string Pos_CommentField;
        
        private string Pos_CustomerActivityTypeCodeField;
        
        private string Pos_ErrorField;
        
        private string Pos_FalseBrochureProgramCodeField;
        
        private bool Pos_HasInfoMeetingField;
        
        private bool Pos_HasPQField;
        
        private bool Pos_HasReservationField;
        
        private bool Pos_HasTargetMarketingField;
        
        private bool Pos_IsIncorrectProductField;
        
        private bool Pos_IsJuniorField;
        
        private bool Pos_IsManualImportField;
        
        private bool Pos_IsUPField;
        
        private string Pos_LanguageField;
        
        private string Pos_MarketCodeField;
        
        private string Pos_MultiCampaignProgramField;
        
        private string Pos_MyEfRepAtInterestNameField;
        
        private int Pos_MyEfRepAtInterest_IdField;
        
        private int Pos_MyEfRepMarket_IdField;
        
        private int Pos_ProcessStatusField;
        
        private string Pos_ProductCodeField;
        
        private string Pos_ProgramCodeField;
        
        private string Pos_RegionNameField;
        
        private string Pos_SalesOfficeField;
        
        private int Pos_SchoolIDField;
        
        private string Pos_ShippingNotesField;
        
        private int Pos_Title_IdField;
        
        private bool Pos_isMultiProgramField;
        
        private string PostalCodeField;
        
        private string ProgramCodeField;
        
        private string RegionField;
        
        private string SchoolCityField;
        
        private string SchoolCountryCodeField;
        
        private string SchoolNameField;
        
        private int SchoolUniPoseidon_IdField;
        
        private string SchoolUniSizeField;
        
        private string SecondaryProgramCodesField;
        
        private string StateField;
        
        private int pos_Company_IdField;
        
        private string pos_Company_NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CalledFromMassageService
        {
            get
            {
                return this.CalledFromMassageServiceField;
            }
            set
            {
                this.CalledFromMassageServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignAllocationCode
        {
            get
            {
                return this.CampaignAllocationCodeField;
            }
            set
            {
                this.CampaignAllocationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignAllocationPrograms
        {
            get
            {
                return this.CampaignAllocationProgramsField;
            }
            set
            {
                this.CampaignAllocationProgramsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignName
        {
            get
            {
                return this.CampaignNameField;
            }
            set
            {
                this.CampaignNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerActivityTypeCode
        {
            get
            {
                return this.CustomerActivityTypeCodeField;
            }
            set
            {
                this.CustomerActivityTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EFComRepresentativeMarket_Id
        {
            get
            {
                return this.EFComRepresentativeMarket_IdField;
            }
            set
            {
                this.EFComRepresentativeMarket_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EFComRepresentative_Id
        {
            get
            {
                return this.EFComRepresentative_IdField;
            }
            set
            {
                this.EFComRepresentative_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EfComMarketCode
        {
            get
            {
                return this.EfComMarketCodeField;
            }
            set
            {
                this.EfComMarketCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnqFormType
        {
            get
            {
                return this.EnqFormTypeField;
            }
            set
            {
                this.EnqFormTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntrySourceCode
        {
            get
            {
                return this.EntrySourceCodeField;
            }
            set
            {
                this.EntrySourceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormSubmission_id
        {
            get
            {
                return this.FormSubmission_idField;
            }
            set
            {
                this.FormSubmission_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormUrl
        {
            get
            {
                return this.FormUrlField;
            }
            set
            {
                this.FormUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Infomeeting_Id
        {
            get
            {
                return this.Infomeeting_IdField;
            }
            set
            {
                this.Infomeeting_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InsertDate
        {
            get
            {
                return this.InsertDateField;
            }
            set
            {
                this.InsertDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExpressCall
        {
            get
            {
                return this.IsExpressCallField;
            }
            set
            {
                this.IsExpressCallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LanguageCode
        {
            get
            {
                return this.LanguageCodeField;
            }
            set
            {
                this.LanguageCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyEFInvitationRepresentativeMarket_Id
        {
            get
            {
                return this.MyEFInvitationRepresentativeMarket_IdField;
            }
            set
            {
                this.MyEFInvitationRepresentativeMarket_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyEFInvitationRepresentative_Id
        {
            get
            {
                return this.MyEFInvitationRepresentative_IdField;
            }
            set
            {
                this.MyEFInvitationRepresentative_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_Comment
        {
            get
            {
                return this.Pos_CommentField;
            }
            set
            {
                this.Pos_CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_CustomerActivityTypeCode
        {
            get
            {
                return this.Pos_CustomerActivityTypeCodeField;
            }
            set
            {
                this.Pos_CustomerActivityTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_Error
        {
            get
            {
                return this.Pos_ErrorField;
            }
            set
            {
                this.Pos_ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_FalseBrochureProgramCode
        {
            get
            {
                return this.Pos_FalseBrochureProgramCodeField;
            }
            set
            {
                this.Pos_FalseBrochureProgramCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_HasInfoMeeting
        {
            get
            {
                return this.Pos_HasInfoMeetingField;
            }
            set
            {
                this.Pos_HasInfoMeetingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_HasPQ
        {
            get
            {
                return this.Pos_HasPQField;
            }
            set
            {
                this.Pos_HasPQField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_HasReservation
        {
            get
            {
                return this.Pos_HasReservationField;
            }
            set
            {
                this.Pos_HasReservationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_HasTargetMarketing
        {
            get
            {
                return this.Pos_HasTargetMarketingField;
            }
            set
            {
                this.Pos_HasTargetMarketingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_IsIncorrectProduct
        {
            get
            {
                return this.Pos_IsIncorrectProductField;
            }
            set
            {
                this.Pos_IsIncorrectProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_IsJunior
        {
            get
            {
                return this.Pos_IsJuniorField;
            }
            set
            {
                this.Pos_IsJuniorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_IsManualImport
        {
            get
            {
                return this.Pos_IsManualImportField;
            }
            set
            {
                this.Pos_IsManualImportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_IsUP
        {
            get
            {
                return this.Pos_IsUPField;
            }
            set
            {
                this.Pos_IsUPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_Language
        {
            get
            {
                return this.Pos_LanguageField;
            }
            set
            {
                this.Pos_LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_MarketCode
        {
            get
            {
                return this.Pos_MarketCodeField;
            }
            set
            {
                this.Pos_MarketCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_MultiCampaignProgram
        {
            get
            {
                return this.Pos_MultiCampaignProgramField;
            }
            set
            {
                this.Pos_MultiCampaignProgramField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_MyEfRepAtInterestName
        {
            get
            {
                return this.Pos_MyEfRepAtInterestNameField;
            }
            set
            {
                this.Pos_MyEfRepAtInterestNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_MyEfRepAtInterest_Id
        {
            get
            {
                return this.Pos_MyEfRepAtInterest_IdField;
            }
            set
            {
                this.Pos_MyEfRepAtInterest_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_MyEfRepMarket_Id
        {
            get
            {
                return this.Pos_MyEfRepMarket_IdField;
            }
            set
            {
                this.Pos_MyEfRepMarket_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_ProcessStatus
        {
            get
            {
                return this.Pos_ProcessStatusField;
            }
            set
            {
                this.Pos_ProcessStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_ProductCode
        {
            get
            {
                return this.Pos_ProductCodeField;
            }
            set
            {
                this.Pos_ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_ProgramCode
        {
            get
            {
                return this.Pos_ProgramCodeField;
            }
            set
            {
                this.Pos_ProgramCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_RegionName
        {
            get
            {
                return this.Pos_RegionNameField;
            }
            set
            {
                this.Pos_RegionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_SalesOffice
        {
            get
            {
                return this.Pos_SalesOfficeField;
            }
            set
            {
                this.Pos_SalesOfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_SchoolID
        {
            get
            {
                return this.Pos_SchoolIDField;
            }
            set
            {
                this.Pos_SchoolIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pos_ShippingNotes
        {
            get
            {
                return this.Pos_ShippingNotesField;
            }
            set
            {
                this.Pos_ShippingNotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pos_Title_Id
        {
            get
            {
                return this.Pos_Title_IdField;
            }
            set
            {
                this.Pos_Title_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pos_isMultiProgram
        {
            get
            {
                return this.Pos_isMultiProgramField;
            }
            set
            {
                this.Pos_isMultiProgramField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode
        {
            get
            {
                return this.ProgramCodeField;
            }
            set
            {
                this.ProgramCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolCity
        {
            get
            {
                return this.SchoolCityField;
            }
            set
            {
                this.SchoolCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolCountryCode
        {
            get
            {
                return this.SchoolCountryCodeField;
            }
            set
            {
                this.SchoolCountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolName
        {
            get
            {
                return this.SchoolNameField;
            }
            set
            {
                this.SchoolNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SchoolUniPoseidon_Id
        {
            get
            {
                return this.SchoolUniPoseidon_IdField;
            }
            set
            {
                this.SchoolUniPoseidon_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolUniSize
        {
            get
            {
                return this.SchoolUniSizeField;
            }
            set
            {
                this.SchoolUniSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryProgramCodes
        {
            get
            {
                return this.SecondaryProgramCodesField;
            }
            set
            {
                this.SecondaryProgramCodesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int pos_Company_Id
        {
            get
            {
                return this.pos_Company_IdField;
            }
            set
            {
                this.pos_Company_IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pos_Company_Name
        {
            get
            {
                return this.pos_Company_NameField;
            }
            set
            {
                this.pos_Company_NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EFTrueProgramCodeService.IEFPosProgramConversionService")]
    public interface IEFPosProgramConversionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEFPosProgramConversionService/GetPosProgramCode", ReplyAction="http://tempuri.org/IEFPosProgramConversionService/GetPosProgramCodeResponse")]
        System.Threading.Tasks.Task<string> GetPosProgramCodeAsync(EFTrueProgramCodeService.WebFormSubmission wfs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEFPosProgramConversionService/GetPOSWebFormSubmission", ReplyAction="http://tempuri.org/IEFPosProgramConversionService/GetPOSWebFormSubmissionResponse" +
            "")]
        System.Threading.Tasks.Task<EFTrueProgramCodeService.WebFormSubmission[]> GetPOSWebFormSubmissionAsync(EFTrueProgramCodeService.WebFormSubmission[] listwfs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IEFPosProgramConversionServiceChannel : EFTrueProgramCodeService.IEFPosProgramConversionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class EFPosProgramConversionServiceClient : System.ServiceModel.ClientBase<EFTrueProgramCodeService.IEFPosProgramConversionService>, EFTrueProgramCodeService.IEFPosProgramConversionService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EFPosProgramConversionServiceClient() : 
                base(EFPosProgramConversionServiceClient.GetDefaultBinding(), EFPosProgramConversionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEFPosProgramConversionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EFPosProgramConversionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EFPosProgramConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), EFPosProgramConversionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EFPosProgramConversionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EFPosProgramConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EFPosProgramConversionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EFPosProgramConversionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EFPosProgramConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetPosProgramCodeAsync(EFTrueProgramCodeService.WebFormSubmission wfs)
        {
            return base.Channel.GetPosProgramCodeAsync(wfs);
        }
        
        public System.Threading.Tasks.Task<EFTrueProgramCodeService.WebFormSubmission[]> GetPOSWebFormSubmissionAsync(EFTrueProgramCodeService.WebFormSubmission[] listwfs)
        {
            return base.Channel.GetPOSWebFormSubmissionAsync(listwfs);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEFPosProgramConversionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEFPosProgramConversionService))
            {
                return new System.ServiceModel.EndpointAddress("http://poseidonqa.eflangtech.com/EfComPosProgramConversionService/EfComPosProgram" +
                        "Conversion.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EFPosProgramConversionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEFPosProgramConversionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EFPosProgramConversionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEFPosProgramConversionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEFPosProgramConversionService,
        }
    }
}
